# Testing sign-in
curl -i --location --request POST 'https://ajbaqfkhsjbpkelepjpe.supabase.co/functions/v1/signin' \
   --header 'Content-Type: application/json' \ 
   --data '{"userId": "UB8eNMRCeBLVmIrg59ekFnNx", "exp":"161569516"}'

### 
# Testing task addition
# TODO: Add bearer token to test
curl -i --location --request POST 'https://ajbaqfkhsjbpkelepjpe.supabase.co/functions/v1/restful' \
  --header 'Authorization: Bearer ' \
  --header 'Content-Type: application/json' \
  --data '{"task": {
  "duration": "1500",
  "is_active": "true",
  "start_time": "2023-09-18T14:15:04.486Z",
  "type": "work"}}'

###
# Testing task receiving 
# TODO: Add bearer token to test
curl -i --location --request GET 'https://ajbaqfkhsjbpkelepjpe.supabase.co/functions/v1/restful' \
  --header 'Authorization: Bearer '